### ISSUE TITLE
how to: filtering of nested array objects

### ISSUE THREAD

**Issue by chao10** [Antibrumm/jackson-antpathfilter#10]
Hello,

Thanks for the addon - works great. I have a new request, which is to support filtering of nested array objects. How could achieve that?

For example:
```
{
    "user_id": 123,
    "name": "foo",
    "roles": [
        {
            "name": "ROLE_USER",
            "description": "Regular users."
        },
        {
            "name": "ROLE_ADMIN",
            "description": "Administrators."
        }
    ]
}
```
How to filter out the `roles[*].description` from the above Json string?  Thanks!

**Comment by Antibrumm** [comment]
You should just be able to write `roles.description` as far as I can tell :)

**Comment by Antibrumm** [comment]
Oh and to ignore the output `!roles.description`

**Comment by chao10** [comment]
Thanks for the reply. I had a try of your suggestions but neither worked. Perhaps the AntPathMatcher class doesn't match json strings that contains '[' and ']'. I'm not sure..

**Comment by Antibrumm** [comment]
This should work at least with collections of any kind. Let me add some unit tests as examples. You want to filter out all descriptions from the role objects right?

**Comment by Antibrumm** [comment]
Just checked my test cases and there is actually one:

```
Filter: "reports", "reports.firstName"
Result: {"reports":[{"firstName":"First 0"},{"firstName":"First 1"},{"firstName":"First 2"},{"firstName":"First 3"},{"firstName":"First 4"},{"firstName":"First 5"},{"firstName":"First 6"},{"firstName":"First 7"},{"firstName":"First 8"},{"firstName":"First 9"}]}
```

Filtering collections by specific elements itself is not implemented (i.e `reports[5]`) and I don't think this was your intention. Just remove your brackets and you should be fine. :)
