### ISSUE TITLE
Support objects other than java beans

### ISSUE THREAD

**Issue by vtipparam** [Antibrumm/jackson-antpathfilter#11]
I have a requirement to filter Json objects using Ant like paths. AntPathFilter library sounds like a perfect solution but unfortunately my data is in flexible data structures such as Jackson ObjectNode and Java Map. I couldn't get it to work with Jackson ObjectNode.

```
	@Test
	public void testAntPathFilterObject()  throws Exception {
		ObjectNode user = JsonNodeFactory.instance.objectNode();
		user.put("name", "Venkat").put("dept", "Eng").putObject("manager").put("name", "Scot").put("dept", "Eng");
		
		String[] filter = new String[] {"!manager"};

		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.addMixIn(Object.class, AntPathFilterMixin.class);

		FilterProvider filterProvider = new SimpleFilterProvider().addFilter("antPathFilter", new AntPathPropertyFilter(filter));
		objectMapper.setFilters(filterProvider);

		String json = objectMapper.writeValueAsString(user);
		System.out.println("json="+json);
	}
```

This gives me

`json={"name":"Venkat","dept":"Eng","manager":{"name":"Scot","dept":"Eng"}}
`

But the following code with POJO works as expected:

```
	public void testAntPathFilterPOJO() throws Exception {
		User user = new User();
		User manager = new User();
		
		manager.setName("Scot");
		manager.setDept("Eng");
		
		user.setName("Venkat");
		user.setDept("Eng");
		user.setManager(manager);
		
		String[] filter = new String[] {"!manager"};

		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.addMixIn(Object.class, AntPathFilterMixin.class);

		FilterProvider filterProvider = new SimpleFilterProvider().addFilter("antPathFilter", new AntPathPropertyFilter(filter));
		objectMapper.setFilters(filterProvider);

		String json = objectMapper.writeValueAsString(user);
		System.out.println("json="+json);
	}
```

This produces intended result:

`json={"name":"Venkat","dept":"Eng"}
`

Does the library work with non-POJOs? It will be great to have AntPathFilter working with non-POJO such as Jackson JsonNode, Map, etc.

**Comment by vtipparam** [comment]
Just tested with Map and it seems to work.

```
	public void testAntPathFilterMap()  throws Exception {
		Map<String,Object> user = new HashMap<>();
		Map<String,Object> manager = new HashMap<>();
		user.put("name", "Venkat");
		user.put("dept", "Eng");
		user.put("manager", manager);
		manager.put("name", "Scot");
		manager.put("dept", "Eng");
		
		String[] filter = new String[] {"!manager"};

		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.addMixIn(Object.class, AntPathFilterMixin.class);

		FilterProvider filterProvider = new SimpleFilterProvider().addFilter("antPathFilter", new AntPathPropertyFilter(filter));
		objectMapper.setFilters(filterProvider);

		String json = objectMapper.writeValueAsString(user);
		System.out.println("json="+json);
	}
```

Output:

`json={"name":"Venkat","dept":"Eng"}
`

It appears the issue is with Jackson ObjectNode. Is this expected behavior?

Thanks,
Venkat

**Comment by Antibrumm** [comment]
I will have to check what the pathToTest looks like in this case. I think objectnode uses an iterator and is not an implementation of `Map`, so the path that i check for filtering should look somehow different. Thanks for the testcase, I will use that to dig :)

**Comment by Antibrumm** [comment]
I took a quick look at this and found out that the ObjectNode has his own implementation of how it is writing the json structure. In fact it's never calling the `serializeFiltered` methods as ObjectNode, and most likely any JsonNode, implements `JsonSerializable`. 

**Most likely this is a design decision from Jackson.**

So there is nothing that the AntpathFilter can do about that. The filtering mechanism is simply ignored by this implementation: 
*Interface that can be implemented by objects that know how to serialize themselves to JSON*

You could ask about that on the issue page for jackson-databind, or implement an extended version of the `JsonNode` structures to support the call to filtered serialization.

Most likely the simplest approach, for the moment, is to use a Map implementation to fulfill your requirement of dynamic structures.

**Comment by vtipparam** [comment]
Thanks a lot for looking into this. Really appreciate your help! I have migrated all my flexible data structures to Map to address the issue for now. Also I will post on jackson-databind issues page as you suggested.

Thanks again for your awesome filter library. It saved me a ton of time.
