### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded with version 1.0.2

### ISSUE THREAD

**Issue by jluismoran** [Antibrumm/jackson-antpathfilter#13]
Hi. I'm using version 1.0.0 and when there is a loop in collections, I get "infinite recursion" Jackson error showing the relation that is causing the problem but when I've tested new version 1.0.2, I'm only getting "java.lang.OutOfMemoryError: GC overhead limit" error, without any other useful information. Because that I'm using the previous version again.

Your library is very useful to deal with collections, using JPA and REST. So, I'll be attentive to new releases. Thank you very much.

**Comment by Antibrumm** [comment]
This is most likely due to an infinite loop in an entity graph like `Author -> books -> authors ->...` 
You will have to break the cycle by limiting the output to three levels for example or by using explict inclusion filters on the property like `*.books, *.books.name`
