### ISSUE TITLE
Investigate performance improvement potential

### ISSUE THREAD

**Issue by Antibrumm** [Antibrumm/jackson-antpathfilter#5]
Havent really tested performance of the filter itself yet. Would be good to gather some ideas of how to improve it for complex objects.

**Comment by krishna81m** [comment]
Here is an draft working idea that avoids building paths and each time. Assumes same properties of a given class  are filtered no matter how many different instances of the same class are used. Although, already have thought of a fix for this issue as well by maintaining property names that are of the same class type. 

Either way, there was hardly any performance loss (compared to no filters) with this approach as we cache properties as a filter just once per Jackson root entity and all its nested properties that are being filtered. In fact, very fast when there were very few properties per class:

https://github.com/krishna81m/jackson-nested-prop-filter

Let me know your thoughts.

**Comment by Antibrumm** [comment]
The idea of the antpath filter was exactly that the same class needs to be filtered differently depending on it's position in the object tree. The test case uses a user class toplevel as well as for the manager attributes. 

I wonder if your filter and mine have similar performance in case we dont have wildcards in the filter description? I will do a benchmark on that locally :)

Do you support wildcards? I think your filter approach is nice in case we need a higher performance vs wildcard matching.

**Comment by Antibrumm** [comment]
No further improvement planned for now
