### ISSUE TITLE
Use with JAX-RS

### ISSUE THREAD

**Issue by heruan** [Antibrumm/jackson-antpathfilter#7]
How to use it with JAX-RS? I tried to set the filter in a `WriterInterceptor` but subsequent HTTP requests overlaps property filters and the outcome becomes unpredictable.

**Comment by Antibrumm** [comment]
I havent used it together with jax-rs. But a quick search on stackoverflow showed some interesting approaches:

http://stackoverflow.com/questions/9314735/how-to-return-a-partial-json-response-using-java

Check the second answer, not the accepted one.

You will need to modify the object mapper. I dont know if you can use mix-ins.

**Comment by Antibrumm** [comment]
Please reopen if you need some support :)
