### ISSUE TITLE
addMixInAnnotations instead of addMixIn

### ISSUE THREAD

**Issue by perotom** [Antibrumm/jackson-antpathfilter#8]
To make the example working i had to change this line:
`mapper.addMixIn(Object.class, AntPathFilterMixin.class);`
to
`mapper.addMixInAnnotations(Object.class, AntPathFilterMixin.class);`

I am using jackson 2.8.1

**Comment by Antibrumm** [comment]
Thanks for the info. Looks like this is a change in the API of jackson. I will update this once i have some spare time.

**Comment by Antibrumm** [comment]
Just checked the API and found this:

```
    /**
     * @deprecated Since 2.5: replaced by a fluent form of the method; {@link #setMixIns}.
     */
    @Deprecated
    public void setMixInAnnotations
```
