### ISSUE TITLE
antPathFilter seems to be the only supported filter name

### ISSUE THREAD

**Issue by NeverNude** [Antibrumm/jackson-antpathfilter#9]
If I try to configure other AntPathPropertyFilters with different names (e.g. MyService -> new AntPathPropertyFilter("**.someproperty") it appears to fail.  The library also appears to work only as long as you have a filter of the name antPathFilter.  Is there some workaround to allow different names for the path filter?  It's entirely possible that I've just missed something, but it wasn't obvious fooling around with it for ~1 hour.

**Comment by Antibrumm** [comment]
Havent thought about the name, i will give it a try. How do you want to use multiple filters?

Just like that i would say that the registration of the filter needs to happen only once as the filter itself is dynamic. Multiple mixins should be possible with the same filter name, but on other classes (if its not on Object). I dont know if you can mix MixIns.

**Comment by Antibrumm** [comment]
Take a look at the test class
https://github.com/Antibrumm/jackson-antpathfilter/blob/master/src/test/java/ch/mfrey/jackson/antpathfilter/test/AntPathFilterTest.java

Registering the filter by a name is not the same as using the filter to produce dynamic outcomes. Normal use case would be to register the filter once `@JsonFilter("antPathFilterOtherName")` and register the filter on the `ObjectMapper` with `new SimpleFilterProvider().addFilter("antPathFilterOtherName", new AntPathPropertyFilter(filters));`

I haven't tried this, but I would think that you could register multiple filter configurations at the same time with this approach. I myself did not have to do this in my project as the class `Jackson2Helper` copies the `ObjectMapper` and then applies the filter.
